# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_remove_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
