# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20160907_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('image', models.FileField(blank=True, null=True, upload_to='client/')),
                ('order', models.CharField(blank=True, max_length=15)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
