# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverimage',
            name='featured',
            field=models.NullBooleanField(),
        ),
    ]
