# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-25 12:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_coverimage_featured'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coverimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='coverimage',
            name='order',
        ),
        migrations.RemoveField(
            model_name='coverimage',
            name='text',
        ),
    ]
