# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0009_auto_20160926_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_about', models.CharField(max_length=700)),
                ('fb', models.BooleanField()),
                ('fb_url', models.CharField(max_length=100)),
                ('tw', models.BooleanField()),
                ('tw_url', models.CharField(max_length=100)),
                ('insta', models.BooleanField()),
                ('insta_url', models.CharField(max_length=100)),
                ('google_plus', models.BooleanField()),
                ('google_url', models.CharField(max_length=100)),
                ('pinterest', models.BooleanField()),
                ('pinterest_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IzabelaAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('izabela_about', models.CharField(max_length=700)),
                ('fb', models.BooleanField()),
                ('fb_url', models.CharField(max_length=100)),
                ('tw', models.BooleanField()),
                ('tw_url', models.CharField(max_length=100)),
                ('insta', models.BooleanField()),
                ('insta_url', models.CharField(max_length=100)),
                ('google_plus', models.BooleanField()),
                ('google_url', models.CharField(max_length=100)),
                ('pinterest', models.BooleanField()),
                ('pinterest_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='KeithAbout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keith_about', models.CharField(max_length=700)),
                ('fb', models.BooleanField()),
                ('fb_url', models.CharField(max_length=100)),
                ('tw', models.BooleanField()),
                ('tw_url', models.CharField(max_length=100)),
                ('insta', models.BooleanField()),
                ('insta_url', models.CharField(max_length=100)),
                ('google_plus', models.BooleanField()),
                ('google_url', models.CharField(max_length=100)),
                ('pinterest', models.BooleanField()),
                ('pinterest_url', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='about',
        ),
    ]
