# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_auto_20160926_0738'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IzabelaAbout',
        ),
        migrations.DeleteModel(
            name='KeithAbout',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='cover/'),
        ),
    ]
