# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20160926_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='coverimage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
