# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 07:02
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_auto_20160927_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=tinymce.models.HTMLField(blank=True, max_length=500),
        ),
    ]
