# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 07:09
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_auto_20160927_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(blank=True, max_length=500)),
                ('featured', models.BooleanField(default=False)),
                ('name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
