# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_auto_20160927_0910'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='izabela_image',
            field=models.FileField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='keith_image',
            field=models.FileField(blank=True, null=True, upload_to='about/'),
        ),
    ]
