# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-27 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_auto_20160927_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
