# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_auto_20160927_0958'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyAbout',
        ),
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': '4. About Us', 'verbose_name_plural': '4. About Us'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['order'], 'verbose_name': '5. Client', 'verbose_name_plural': '5. Clients'},
        ),
        migrations.AlterModelOptions(
            name='coverimage',
            options={'verbose_name': '1. Home', 'verbose_name_plural': '1. Home'},
        ),
        migrations.AlterModelOptions(
            name='ourservices',
            options={'verbose_name': '2. Services', 'verbose_name_plural': '2. Services'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['order'], 'verbose_name': '3. Projects', 'verbose_name_plural': '3. Projects'},
        ),
        migrations.AddField(
            model_name='aboutus',
            name='izabela_image_2',
            field=models.FileField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='keith_image_2',
            field=models.FileField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=tinymce.models.HTMLField(blank=True, max_length=500),
        ),
    ]
