# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-06 08:04
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_auto_20160929_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='izabela_name_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='izabela_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='keith_name_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='aboutus',
            name='keith_position',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='ourservices',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
    ]
